Repository catalyst-network/Catalyst, pull requests merged in 2019-10, with the labels that each got.

#1062 Remove duplicate package references
  src/Catalyst.Core.Modules.Hashing.Tests/Catalyst.Core.Modules.Hashing.Tests.csproj
Labels: Pull Request 🕵️

#1063 Fix tests and upgrade for .net 3.0
  src/Catalyst.Abstractions/Keystore/IKeystore.cs
  src/Catalyst.Core.Lib.Tests/IntegrationTests/P2P/PeerSettingsTests.cs
  src/Catalyst.Core.Lib.Tests/IntegrationTests/P2P/PeerValidationIntegrationTest.cs
  src/Catalyst.Core.Lib.Tests/UnitTests/DAO/DaoTests.cs
  src/Catalyst.Core.Lib.Tests/UnitTests/P2P/IO/Transport/Channels/PeerClientChannelFactoryTests.cs
  src/Catalyst.Core.Lib/P2P/PeerSettings.cs
  src/Catalyst.Core.Modules.Consensus.Tests/UnitTests/ConsensusTests.cs
  src/Catalyst.Core.Modules.Consensus.Tests/UnitTests/Deltas/DeltaBuilderTests.cs
  src/Catalyst.Core.Modules.Consensus.Tests/UnitTests/IO/Observers/CandidateDeltaObserverTests.cs
  src/Catalyst.Core.Modules.Consensus.Tests/UnitTests/IO/Observers/FavouriteDeltaObserverTests.cs
  src/Catalyst.Core.Modules.Consensus/Consensus.cs
  src/Catalyst.Core.Modules.Consensus/Deltas/DeltaBuilder.cs
  src/Catalyst.Core.Modules.Consensus/IO/Observers/CandidateDeltaObserver.cs
  src/Catalyst.Core.Modules.Consensus/IO/Observers/FavouriteDeltaObserver.cs
  src/Catalyst.Core.Modules.Hashing.Tests/Catalyst.Core.Modules.Hashing.Tests.csproj
  src/Catalyst.Core.Modules.KeySigner.Tests/IntegrationTests/KeySignerIntegrationTests.cs
  src/Catalyst.Core.Modules.KeySigner.Tests/UnitTests/KeySignerTests.cs
  src/Catalyst.Core.Modules.KeySigner/KeySigner.cs
  src/Catalyst.Core.Modules.Keystore.Tests/IntegrationTests/LocalKeyStoreTests.cs
  src/Catalyst.Core.Modules.Keystore/LocalKeyStore.cs
  src/Catalyst.Core.Modules.Web3/ApiModule.cs
  src/Catalyst.KeyGenerator/Commands/GenerateKeyStore.cs
  src/Catalyst.KeyGenerator/Commands/LoadKeyStore.cs
  src/Catalyst.KeyGenerator/Core/Startup.cs
  src/Catalyst.KeyGenerator/Interfaces/IKeyGeneratorCommand.cs
  src/Catalyst.Simulator/RpcClients/SimpleRPCClient.cs
  src/Catalyst.TestUtils/Catalyst.TestUtils.csproj
  src/Catalyst.TestUtils/Config/AuthCredentials.xml
  src/Catalyst.TestUtils/Config/devnet.json
  src/Catalyst.TestUtils/Config/mainnet.json
  src/Catalyst.TestUtils/Config/nodes.json
  src/Catalyst.TestUtils/Config/testnet.json
  src/Catalyst.TestUtils/ContainerProvider.cs
  src/Catalyst.TestUtils/DeltaHelper.cs
Labels: Enhancement 👷, Pull Request 🕵️

#1065 move node build scripts to node project, async fixes on kernel
  Dockerfile
  Vagrantfile
  devnet-docker-compose.yml
  src/Catalyst.Core.Lib/Kernel/Kernel.cs
Labels: Enhancement 👷

#1066 Fix nuget
  nuget-pre-release-azure-pipelines.yml
  pr-test-suite-azure-pipelines.yml
  src/Catalyst.Core.Lib/P2P/PeerSettings.cs
  src/Catalyst.Core.Modules.Cryptography.BulletProofs/Catalyst.Core.Modules.Cryptography.BulletProofs.csproj
Labels: Bug 🐛, Enhancement 👷

#1084 Add more windows instructions for rust install
  README.md
Labels: Pull Request 🕵️

#1081 Fix compiler warnings
  src/Catalyst.Abstractions/Network/IDns.cs
  src/Catalyst.Core.Lib.Tests/IntegrationTests/Rpc/IO/Observers/SignMessageRequestObserverTests.cs
  src/Catalyst.Core.Lib/IO/Events/TransactionReceivedEvent.cs
  src/Catalyst.Core.Lib/IO/Handlers/AuthenticationHandler.cs
  src/Catalyst.Core.Lib/IO/Observers/RequestObserverBase.cs
  src/Catalyst.Core.Lib/IO/Transport/SocketBase.cs
  src/Catalyst.Core.Lib/Network/DevDnsClient.cs
  src/Catalyst.Core.Lib/Network/DnsClient.cs
  src/Catalyst.Core.Lib/Network/Ip.cs
  src/Catalyst.Core.Lib/P2P/ReputationSystem/IReputationManager.cs
  src/Catalyst.Core.Lib/P2P/ReputationSystem/ReputationManager.cs
  src/Catalyst.Core.Modules.Consensus.Tests/UnitTests/Deltas/DeltaHubTests.cs
  src/Catalyst.Core.Modules.Consensus/Deltas/DeltaDfsReader.cs
  src/Catalyst.Core.Modules.Consensus/Deltas/DeltaHub.cs
  src/Catalyst.Core.Modules.Dfs.Tests/IntegrationTests/NodeFileTransferTests.cs
  src/Catalyst.Core.Modules.Dfs/Dfs.cs
  src/Catalyst.Core.Modules.KeySigner/KeySigner.cs
  src/Catalyst.Core.Modules.P2P.Discovery.Hastings.Tests/UnitTests/HastingsDiscoveryTests.cs
  src/Catalyst.Core.Modules.P2P.Discovery.Hastings/HastingsDiscovery.cs
  src/Catalyst.Core.Modules.Rpc.Client/IO/Observers/GetFileFromDfsResponseObserver.cs
  src/Catalyst.Core.Modules.Rpc.Server.Tests/UnitTests/AddFileToDfsRequestObserverTests.cs
  src/Catalyst.Core.Modules.Rpc.Server/IO/Observers/AddFileToDfsRequestObserver.cs
  src/Catalyst.Core.Modules.Rpc.Server/IO/Observers/GetFileFromDfsRequestObserver.cs
  src/Catalyst.Core.Modules.Rpc.Server/RpcServerModule.cs
  src/Catalyst.Core.Modules.Web3/ApiModule.cs
  src/Catalyst.Modules.POA.P2P.Discovery.Consortium/Discovery/PoaDiscovery.cs
  src/Catalyst.TestUtils/DiscoveryHelper.cs
  src/Catalyst.TestUtils/FileHelper.cs
Labels: Pull Request 🕵️

#1085 As a developer I would like to use the mempool web api controller in .net 3.0
  src/Catalyst.Core.Lib/Validators/TransactionValidator.cs
  src/Catalyst.Core.Modules.Web3.Tests/UnitTests/ApiModuleTests.cs
  src/Catalyst.Core.Modules.Web3/ApiModule.cs
  src/Catalyst.Core.Modules.Web3/Catalyst.Core.Modules.Web3.csproj
  src/Catalyst.Core.Modules.Web3/Controllers/MempoolController.cs
Labels: Pull Request 🕵️
