Repository catalyst-network/Catalyst, pull requests merged in 2019-11, with the labels that each got.

#1092 fix 2 discovery tests
  src/Catalyst.Core.Modules.P2P.Discovery.Hastings.Tests/IntegrationTests/HastingsDiscoveryTests.cs
  src/Catalyst.Core.Modules.P2P.Discovery.Hastings.Tests/UnitTests/HastingsDiscoveryTests.cs
Labels: Enhancement 👷

#1097 Fix ledger controller
  src/Catalyst.Core.Lib/DAO/Deltas/DeltaDao.cs
  src/Catalyst.Core.Lib/Util/CidHelper.cs
  src/Catalyst.Core.Modules.Web3/ApiModule.cs
  src/Catalyst.Core.Modules.Web3/Controllers/LedgerController.cs
Labels: Pull Request 🕵️

#1098 Use public properties instead of internal for BaseEntryDao as they are not stored.
  src/Catalyst.Core.Lib/DAO/BaseEntryDao.cs
Labels: Pull Request 🕵️

#1095 Azure pipelines
  nuget-pre-release-azure-pipelines.yml
Labels: Pull Request 🕵️

#1100 Update pr-test-suite-azure-pipelines.yml for Azure Pipelines
  pr-test-suite-azure-pipelines.yml
Labels: Pull Request 🕵️

#1099 Add attribute to DaoBase to map to property Id to id
  src/Catalyst.Core.Lib/DAO/DaoBase.cs
Labels: Pull Request 🕵️

#1109 754 unit test config value parser
  src/Catalyst.Core.Lib.Tests/UnitTests/Config/ConfigValueParserTests.cs
Labels: Pull Request 🕵️

#1108 Remove repository wrapper
  src/Catalyst.Abstractions/Mempool/Repositories/IMempoolRepository.cs
  src/Catalyst.Abstractions/Repository/IRepositoryWrapper.cs
  src/Catalyst.Core.Lib.Tests/UnitTests/P2P/IO/Messaging/Broadcast/BroadcastManagerTests.cs
  src/Catalyst.Core.Lib.Tests/UnitTests/P2P/IO/Observers/GetNeighbourRequestObserverTests.cs
  src/Catalyst.Core.Lib.Tests/UnitTests/Rpc/IO/Observers/GetPeerInfoRequestObserverTests.cs
  src/Catalyst.Core.Lib.Tests/UnitTests/Rpc/IO/Observers/RemovePeerRequestObserverTests.cs
  src/Catalyst.Core.Lib/P2P/IO/Messaging/Broadcast/BroadcastManager.cs
  src/Catalyst.Core.Lib/P2P/IO/Observers/GetNeighbourRequestObserver.cs
  src/Catalyst.Core.Lib/P2P/Repository/IPeerRepository.cs
  src/Catalyst.Core.Lib/P2P/Repository/PeerRepository.cs
  src/Catalyst.Core.Lib/Repository/RepositoryWrapper.cs
  src/Catalyst.Core.Modules.Authentication/Repository/AuthCredentialRepository.cs
  src/Catalyst.Core.Modules.Authentication/Repository/IAuthCredentialRepository.cs
  src/Catalyst.Core.Modules.Authentication/RepositoryAuthenticationStrategy.cs
  src/Catalyst.Core.Modules.Consensus.Tests/UnitTests/Deltas/DeltaBuilderTests.cs
  src/Catalyst.Core.Modules.Ledger.Tests/IntegrationTests/LedgerKvmTests.cs
  src/Catalyst.Core.Modules.Ledger.Tests/UnitTests/LedgerTests.cs
  src/Catalyst.Core.Modules.Ledger/Catalyst.Core.Modules.Ledger.csproj
  src/Catalyst.Core.Modules.Ledger/ILedger.cs
  src/Catalyst.Core.Modules.Ledger/LedgerModule.cs
  src/Catalyst.Core.Modules.Ledger/Repository/AccountRepository.cs
  src/Catalyst.Core.Modules.Ledger/Repository/IAccountRepository.cs
  src/Catalyst.Core.Modules.Mempool/Repositories/MempoolRepository.cs
  src/Catalyst.Core.Modules.Rpc.Server/IO/Observers/GetPeerInfoRequestObserver.cs
  src/Catalyst.Core.Modules.Rpc.Server/IO/Observers/RemovePeerRequestObserver.cs
  src/Catalyst.Modules.POA.P2P.Discovery.Consortium.Tests/UnitTests/PeerHeartbeatCheckerTests.cs
  src/Catalyst.TestUtils/TestMempoolDocumentRepository.cs
  src/Catalyst.sln
Labels: Enhancement 👷, Pull Request 🕵️
