Repository catalyst-network/Catalyst, pull requests merged in 2020-07, with the labels that each got.

#1290 Fix consensus cycle time + cycle sync
  src/Catalyst.Abstractions/Consensus/Cycle/ICycleEventsProvider.cs
  src/Catalyst.Core.Modules.Consensus.Tests/UnitTests/Cycle/CycleEventsProviderRawTests.cs
  src/Catalyst.Core.Modules.Consensus.Tests/UnitTests/Cycle/CycleEventsProviderTests.cs
  src/Catalyst.Core.Modules.Consensus.Tests/UnitTests/IO/Observers/CandidateDeltaObserverTests.cs
  src/Catalyst.Core.Modules.Consensus.Tests/UnitTests/IO/Observers/DeltaDfsHashObserverTests.cs
  src/Catalyst.Core.Modules.Consensus.Tests/UnitTests/IO/Observers/FavouriteDeltaObserverTests.cs
  src/Catalyst.Core.Modules.Consensus/Consensus.cs
  src/Catalyst.Core.Modules.Consensus/ConsensusModule.cs
  src/Catalyst.Core.Modules.Consensus/Cycle/CycleConfiguration.cs
  src/Catalyst.Core.Modules.Consensus/Cycle/CycleEventsProvider.cs
  src/Catalyst.Core.Modules.Consensus/Cycle/CycleEventsProviderRaw.cs
  src/Catalyst.Core.Modules.Consensus/Deltas/Building/DeltaBuilder.cs
  src/Catalyst.Core.Modules.Consensus/Deltas/DeltaHub.cs
  src/Catalyst.Core.Modules.Consensus/Deltas/DeltaVoter.cs
  src/Catalyst.Core.Modules.Consensus/IO/Observers/CandidateDeltaObserver.cs
  src/Catalyst.Core.Modules.Consensus/IO/Observers/DeltaDfsHashObserver.cs
  src/Catalyst.Core.Modules.Consensus/IO/Observers/FavouriteDeltaObserver.cs
  src/Catalyst.Core.Modules.Dfs/LibP2P/CatalystProtocol.cs
  src/Catalyst.Core.Modules.Sync.Tests/UnitTests/SyncUnitTests.cs
  src/Catalyst.Core.Modules.Sync/Manager/PeerSyncManager.cs
  src/Catalyst.Core.Modules.Sync/Synchroniser.cs
  src/Catalyst.Core.Modules.Web3/ApiModule.cs
  src/Catalyst.Modules.POA.Consensus.Tests/UnitTests/Deltas/PoaDeltaProducersProviderTests.cs
  src/Catalyst.Modules.POA.Consensus/Deltas/PoaDeltaProducersProvider.cs
  src/Catalyst.Modules.POA.P2P.Discovery.Consortium/Discovery/PoaDiscovery.cs
  src/Catalyst.Node.POA.CE/Program.cs
  src/Catalyst.TestUtils/PoaTestNode.cs
  src/Catalyst.TestUtils/TestCycleEventProvider.cs
  src/Lib.P2P/ISwarmService.cs
  src/Lib.P2P/Routing/DistributedQuery.cs
  src/Lib.P2P/SecureCommunication/Secio1Stream.cs
  src/Lib.P2P/SwarmService.cs
Labels: Bug 🐛, Pull Request 🕵️

#1300 Create CatalystTestPlan.md
  src/CatalystTestPlan.md
Labels: Enhancement 👷, Pull Request 🕵️

#1298 Cycle event provider unit tests
  src/Catalyst.Abstractions/Consensus/Cycle/ICycleEventsProvider.cs
  src/Catalyst.Core.Modules.Consensus.Tests/UnitTests/ConsensusTests.cs
  src/Catalyst.Core.Modules.Consensus.Tests/UnitTests/Cycle/CycleEventsProviderRawTests.cs
  src/Catalyst.Core.Modules.Consensus/Cycle/CycleEventsProviderRaw.cs
  src/Catalyst.Core.Modules.Ledger.Tests/IntegrationTests/TruffleTest/package-lock.json
  src/Catalyst.Core.Modules.Ledger.Tests/IntegrationTests/TruffleTest/package.json
  src/Catalyst.Core.Modules.Ledger.Tests/IntegrationTests/TruffleTest/truffle-config.js - Shortcut.lnk
  src/Lib.P2P/AutoDialer.cs
  src/Lib.P2P/PeerConnection.cs
  src/Lib.P2P/Routing/DhtService.cs
Labels: Enhancement 👷, Pull Request 🕵️

#1302 Add password repeater functionality
  src/Catalyst.Abstractions/Cryptography/IPasswordManager.cs
  src/Catalyst.Abstractions/Cryptography/IPasswordRepeater.cs
  src/Catalyst.Core.Lib.Tests/IntegrationTests/P2P/PeerValidationIntegrationTest.cs
  src/Catalyst.Core.Lib.Tests/UnitTests/Cryptography/PasswordManagerTests.cs
  src/Catalyst.Core.Lib.Tests/UnitTests/Cryptography/PasswordRepeaterTests.cs
  src/Catalyst.Core.Lib/CoreLibProvider.cs
  src/Catalyst.Core.Lib/Cryptography/NodePasswordRepeater.cs
  src/Catalyst.Core.Lib/Cryptography/PasswordManager.cs
  src/Catalyst.Core.Lib/P2P/LocalPeer.cs
  src/Catalyst.TestUtils/ContainerProvider.cs
  src/Catalyst.TestUtils/TestDfs.cs
Labels: Enhancement 👷, Pull Request 🕵️

#1303 RPC call returns tx objects/hashes in block
  src/Catalyst.Core.Modules.Web3/Controllers/Handlers/EthGetBlockByHashHandler.cs
  src/Catalyst.Core.Modules.Web3/Controllers/Handlers/EthGetBlockByNumberHandler.cs
Labels: Pull Request 🕵️
